=== SmallStones/TPhelper/data/scheme/config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="configs">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="category"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="category">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="item"/>
            </xs:sequence>
            <xs:attribute name="id" use="required" type="xs:ID"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="item">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="title"/>
                <xs:choice minOccurs="0" maxOccurs="unbounded">
                    <xs:element ref="file"/>
                    <xs:element ref="document"/>
                    <xs:element ref="infomation"/>
                </xs:choice>
                <xs:element minOccurs="0" ref="subitems"/>
                <xs:element minOccurs="0" ref="examples"/>
            </xs:sequence>
            <xs:attribute name="id" use="required" type="xs:ID"/>
            <xs:attribute name="type">
                <xs:simpleType>
                    <xs:restriction base="xs:token">
                        <xs:enumeration value="any"/>
                        <xs:enumeration value="int"/>
                        <xs:enumeration value="float"/>
                        <xs:enumeration value="boolean"/>
                        <xs:enumeration value="string"/>
                        <xs:enumeration value="array"/>
                        <xs:enumeration value="file"/>
                        <xs:enumeration value="dir"/>
                        <xs:enumeration value="path"/>
                        <xs:enumeration value="word"/>
                        <xs:enumeration value="wordslist"/>
                        <xs:enumeration value="HOST"/>
                        <xs:enumeration value="URL"/>
                        <xs:enumeration value="email"/>
                        <xs:enumeration value=""/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="title" type="xs:string"/>
    <xs:element name="file" type="xs:string"/>
    <xs:element name="document" type="xs:anyURI"/>
    <xs:element name="infomation" type="xs:string"/>
    <xs:element name="subitems">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="subitem"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="subitem">
        <xs:complexType>
            <xs:attribute name="name" type="xs:string"/>
            <xs:attribute name="type">
                <xs:simpleType>
                    <xs:restriction base="xs:token">
                        <xs:enumeration value="any"/>
                        <xs:enumeration value="int"/>
                        <xs:enumeration value="float"/>
                        <xs:enumeration value="boolean"/>
                        <xs:enumeration value="string"/>
                        <xs:enumeration value="array"/>
                        <xs:enumeration value="file"/>
                        <xs:enumeration value="dir"/>
                        <xs:enumeration value="path"/>
                        <xs:enumeration value="word"/>
                        <xs:enumeration value="wordslist"/>
                        <xs:enumeration value="HOST"/>
                        <xs:enumeration value="URL"/>
                        <xs:enumeration value="email"/>
                        <xs:enumeration value=""/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="comment"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="examples">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="example"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="example">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="block">
                    <xs:attribute name="comment" use="required"/>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    <xs:attributeGroup name="checktype">
        <xs:attribute name="type" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:token">
                    <xs:enumeration value="any"/>
                    <xs:enumeration value="int"/>
                    <xs:enumeration value="float"/>
                    <xs:enumeration value="boolean"/>
                    <xs:enumeration value="string"/>
                    <xs:enumeration value="array"/>
                    <xs:enumeration value="file"/>
                    <xs:enumeration value="dir"/>
                    <xs:enumeration value="path"/>
                    <xs:enumeration value="word"/>
                    <xs:enumeration value="wordslist"/>
                    <xs:enumeration value="HOST"/>
                    <xs:enumeration value="URL"/>
                    <xs:enumeration value="email"/>
                    <xs:enumeration value=""/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:attributeGroup>
    <xs:attributeGroup name="attr">
        <xs:attribute name="id" type="xs:ID"/>
        <xs:attribute name="class" type="xs:token"/>
        <xs:attribute name="style" type="xs:string"/>
        <xs:attribute name="title" type="xs:string"/>
    </xs:attributeGroup>
    <xs:element name="div">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="block">
                    <xs:attributeGroup ref="attr"/>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="pre">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="block">
                    <xs:attributeGroup ref="attr"/>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="p">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="block">
                    <xs:attributeGroup ref="attr"/>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="em">
        <xs:complexType mixed="true">
            <xs:group ref="inline"/>
            <xs:attributeGroup ref="attr"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="span">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="block">
                    <xs:attributeGroup ref="attr"/>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="a">
        <xs:complexType mixed="true">
            <xs:group ref="inline"/>
            <xs:attribute name="href" use="required"/>
            <xs:attribute name="target" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:token">
                        <xs:enumeration value="_blank"/>
                        <xs:enumeration value="_top"/>
                        <xs:enumeration value="_self"/>
                        <xs:enumeration value="_parent"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attributeGroup ref="attr"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="strong">
        <xs:complexType mixed="true">
            <xs:group ref="inline"/>
            <xs:attributeGroup ref="attr"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="sub">
        <xs:complexType mixed="true">
            <xs:group ref="inline"/>
            <xs:attributeGroup ref="attr"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="sup">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="block">
                    <xs:attributeGroup ref="attr"/>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="h1">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="block">
                    <xs:attributeGroup ref="attr"/>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="h2">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="block">
                    <xs:attributeGroup ref="attr"/>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="h3">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="block">
                    <xs:attributeGroup ref="attr"/>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="h4">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="block">
                    <xs:attributeGroup ref="attr"/>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="h5">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="block">
                    <xs:attributeGroup ref="attr"/>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="h6">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="block">
                    <xs:attributeGroup ref="attr"/>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="ul">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="li"/>
            </xs:sequence>
            <xs:attributeGroup ref="attr"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="ol">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="li"/>
            </xs:sequence>
            <xs:attributeGroup ref="attr"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="li">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="block">
                    <xs:attributeGroup ref="attr"/>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="i">
        <xs:complexType mixed="true">
            <xs:group ref="inline"/>
            <xs:attributeGroup ref="attr"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="b">
        <xs:complexType mixed="true">
            <xs:group ref="inline"/>
            <xs:attributeGroup ref="attr"/>
        </xs:complexType>
    </xs:element>
    <xs:group name="inline">
        <xs:sequence>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element ref="br"/>
                <xs:element ref="a"/>
                <xs:element ref="b"/>
                <xs:element ref="em"/>
                <xs:element ref="i"/>
                <xs:element ref="sup"/>
                <xs:element ref="sub"/>
                <xs:element ref="strong"/>
                <xs:element ref="span"/>
            </xs:choice>
        </xs:sequence>
    </xs:group>
    <xs:complexType name="block" mixed="true">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:group ref="inline"/>
            <xs:element ref="ul"/>
            <xs:element ref="ol"/>
            <xs:element ref="code"/>
            <xs:element ref="div"/>
            <xs:element ref="pre"/>
            <xs:element ref="p"/>
            <xs:element ref="hr"/>
            <xs:element ref="h1"/>
            <xs:element ref="h2"/>
            <xs:element ref="h3"/>
            <xs:element ref="h4"/>
            <xs:element ref="h5"/>
            <xs:element ref="h6"/>
        </xs:choice>
    </xs:complexType>
    <xs:element name="code">
        <xs:complexType mixed="true">
            <xs:group ref="inline"/>
            <xs:attributeGroup ref="attr"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="hr">
        <xs:complexType>
            <xs:attributeGroup ref="attr"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="br">
        <xs:complexType>
            <xs:attributeGroup ref="attr"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== SmallStones/TPhelper/data/config.xml
<?xml version="1.0"  encoding="UTF-8" ?>
<configs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="scheme/config.xsd">
	<category id="Trace配置">
		<item id="SHOW_PAGE_TRACE">
			<title>Trace界面开启</title>
			<infomation>控制是否在页面底部显示Trace信息,开发是建议开启</infomation>
		</item>
		<item id="TMPL_TRACE_FILE">
			<title>Trace信息模板</title>
			<infomation>设置自定义的Trace信息模板的文件路径</infomation>
			<document>http://doc.thinkphp.cn/manual/page_trace.html</document>
			<examples>
				<example comment="期望配置">
					<code>'TMPL_TRACE_FILE' => APP_PATH.'Public/trace.php'</code>
				</example>
				<example comment="正确填写方式">
					APP_PATH.'Public/trace.php'
				</example>
				<example comment="错误填写方式">
					APP_PATH.Public/trace.php
				</example>
			</examples>
		</item>
		<item id="SHOW_RUN_TIME">
			<title>显示运行状态</title>
			<document>http://doc.thinkphp.cn/manual/app_status.html</document>
			<infomation>开启后在模板底部会显示一行程序执行状态的信息</infomation>
			<examples>
				<example comment="效果示例">
					Process:0.2463s
				</example>
			</examples>
		</item>
		<item id="SHOW_ADV_TIME">
			<title>显示详细运行时间</title>
			<document>http://doc.thinkphp.cn/manual/app_status.html</document>
			<infomation>开启后将在运行状态信息中显示程序从加载到输出结束各个阶段的耗费时间,关闭后只显示总的时间</infomation>
			<examples>
				<example comment="效果示例">
					(Load:0.0003s Init:0.0010s Exec:0.1095s Template:0.1355s )
				</example>
				<example comment="全部信息显示时对应的含义">
					运行信息: 整体执行时间0.2463s ( 加载:0.0003s 初始化:0.0010s 执行:0.1095s 模板:0.1355s ) |
					<br/>
					数据库 :13次读操作 0次写操作 | 缓存：2次读取，0次写入 | 使用内存:415 kb |
					<br/>
					加载文件:20 | 函数调用:63（自定义）,1370（内置）
				</example>
				<example comment="模板中的魔术常量">
					{__RUNTIME__}
				</example>
			</examples>
		</item>
		<item id="SHOW_DB_TIMES">
			<title>显示数据库操作次数</title>
			<infomation>开启后将在运行状态信息中显示数据库读写操作的次数</infomation>
			<document>http://doc.thinkphp.cn/manual/app_status.html</document>
			<examples>
				<example comment="效果示例">
					DB:13 queries 0 writes
				</example>
			</examples>
		</item>
		<item id="SHOW_CACHE_TIMES">
			<title>显示缓存操作次数</title>
			<document>http://doc.thinkphp.cn/manual/app_status.html</document>
			<infomation>开启后将在运行状态信息中显示缓存操作此时</infomation>
			<examples>
				<example comment="效果示例">
					 Cache:2 gets,0 writes
				</example>
			</examples>
		</item>
		<item id="SHOW_USE_MEM">
			<title>显示内存开销</title>
			<document>http://doc.thinkphp.cn/manual/app_status.html</document>
			<infomation>开启后将在运行状态信息中显示页面执行的内存开销</infomation>
			<examples>
				<example comment="效果示例">
					UseMem:1,677 kb
				</example>
			</examples>
		</item>
		<item id="SHOW_LOAD_FILE">
			<title>显示加载文件数量</title>
			<document>http://doc.thinkphp.cn/manual/app_status.html</document>
			<infomation>开启后将在运行状态信息中显示页面执行过程加载的文件总体数量</infomation>
			<examples>
				<example comment="效果示例">LoadFile:20</example>
			</examples>
		</item>
		<item id="SHOW_FUN_TIMES">
			<title>显示函数调用次数</title>
			<infomation>显示执行过程自定义函数(逗号前)调用的次数和系统函数(逗号后)调用的次数</infomation>
			<document>http://doc.thinkphp.cn/manual/app_status.html</document>
			<examples>
				<example comment="效果示例">CallFun:51,2714</example>
			</examples>
		</item>
	</category>
	<category id="URL配置">
		<item id="URL_CASE_INSENSITIVE">
			<title>URL大小写不敏感</title>
			<document>http://doc.thinkphp.cn/manual/url_case.html</document>
			<infomation>设为true后,url将不区分大小写.</infomation>
		</item>
		<item id="URL_PARAMS_BIND">
			<title>Action参数绑定</title>
			<document>http://doc.thinkphp.cn/manual/action_param_bind.html</document>
			<infomation>将url的GET参数与Action方法的参数进行绑定</infomation>
			<examples>
				<example comment="read操作需一个参数$id">
					<code>
						public function read($id=0){ //somecode}
					</code>
				</example>
				<example comment="url为操作提供$id参数">
					<code>
						http://host/index.php/Blog/read/id/5
					</code>
				</example>
			</examples>
		</item>
		<item id="URL_MODEL">
			<title>URL模式</title>
			<infomation>设置url模式</infomation>
			<document>http://doc.thinkphp.cn/manual/url_mode.html</document>
			<examples>
				<example comment="普通模式">
					<code>
						http://host/appName/?m=module&amp;a=action&amp;id=1
					</code>
				</example>
				<example comment="Pathinfo模式">
					<code>
						http://host/appName/module/action/id/1/
					</code>
				</example>
				<example comment="兼容模式">
					<code>
						http://host/appName/?s=/module/action/id/1/
					</code>
				</example>
				<example comment="Rewrite模式">
					使用服务器的Rewrite功能定义URL解析规则
				</example>
			</examples>
		</item>
		<item id="URL_PATHINFO_DEPR">
			<title>Pathinfo模式分隔符</title>
			<document>http://doc.thinkphp.cn/manual/url_mode.html</document>
			<infomation>Pathinfo模式中URL的参数分隔符</infomation>
			<examples>
				<example comment="用~做分隔符号">
					<code>
						http://host/appName/module-action-id-1/
					</code>
				</example>
			</examples>
		</item>
		<item id="URL_HTML_SUFFIX">
			<title>URL伪静态</title>
			<infomation>在pathinfo模式的url尾部增加后缀，支持用 | 设置多个后缀</infomation>
			<document>http://doc.thinkphp.cn/manual/url_suffix.html</document>
			<examples>
				<example comment="设为shtml以后">
					<code>
						http://serverName/Blog/read/id/1.shtml
					</code>
				</example>
				<example comment="希望的配置">
					<code>
						'URL_HTML_SUFFIX'=>'html|shmtl|xml'
					</code>
				</example>
				<example comment="在右边表单填写">
					<code>
						html|shmtl|xml
					</code>
				</example>
				<example comment="错误填写">
					<code>
						html,shmtl,xml
					</code>
				</example>
			</examples>
		</item>
		<item id="URL_ROUTER_ON">
			<title>开启URL路由</title>
			<document>http://doc.thinkphp.cn/manual/url_route.html</document>
			<infomation>开启后可将URL按规则解析后执行</infomation>
		</item>
		<item id="URL_ROUTE_RULES">
			<title>URL路由规则</title>
			<document>http://doc.thinkphp.cn/manual/url_route.html</document>
			<infomation>'路由规则'=>'匹配目标'</infomation>
			<examples>
				<example comment="普通模式格式">
					格式1：路由规则=> 分组/模块/操作?额外参数1=值1&amp;额外参数2=值2...
					<br/>
					格式2：路由规则=> 分组/模块/操作,额外参数1=值1&amp;额外参数2=值2...
					<br/>
					格式3：路由规则=> 外部地址
					<br/>
					格式4：路由规则=> 外部地址,重定向代码
					<br/>
				</example>
				<example comment="REST模式格式">
					格式1：0 => 路由规则或者正则,路由地址,路由额外参数,请求类型,资源类型
					<br/>
					格式2：1 => 路由规则或者正则,外部地址,重定向代码,请求类型,资源类型
					<br/>
					每增加一行，key数字加1填写。
				</example>
			</examples>
		</item>
		<item id="URL_404_REDIRECT">
			<title>404错误重定向URL</title>
			<infomation>一个可直接在浏览器访问的404页面的网址，不能是本地文件路径</infomation>
		</item>
	</category>
	<category id="DB配置">
		<item id="DB_TYPE">
			<title>数据库驱动</title>
			<document>http://doc.thinkphp.cn/manual/connect_database.html</document>
			<infomation>TP核心内置mysql(默认)和mysqli两种驱动,其他驱动需使用Extend类库</infomation>
		</item>
		<item id="DB_HOST">
			<title>数据库主机</title>
			<document>http://doc.thinkphp.cn/manual/connect_database.html</document>
			<infomation>IP、域名或者localhost</infomation>
		</item>
		<item id="DB_PREFIX">
			<title>数据表前缀</title>
			<document>http://doc.thinkphp.cn/manual/connect_database.html</document>
			<infomation>用于避免数据表命名冲突，默认为:think_</infomation>
		</item>
		<item id="DB_DSN">
			<title>数据库默认DSN</title>
			<infomation>设置了DSN则，DSN连接方式优先;分布式数据库不支持DSN设置;驱动为PDO时，采用php的DSN格式;如果你需要多个不同的数据库连接，可以使用数组或DSN方式创建自定义配置，然后在模型中供 $connection属性使用
			</infomation>
			<document>http://doc.thinkphp.cn/manual/connect_database.html</document>
			<examples>
				<example comment="非PDO驱动格式">
					<p>
						数据库类型://用户名:密码@数据库地址:数据库端口/数据库名
					</p>
					<code>
						mysql://username:password@localhost:3306/DbName
					</code>
				</example>
				<example comment="PDO驱动的DSN">
					<code>
						mysql:host=localhost;dbname=thinkphp
					</code>
				</example>
				<example comment="自定义DSN">
					<p>
						<code>
							'MYDSN' => 'mysql://root:1234@localhost:3306/thinkphp';
						</code>
					</p>
					<p>
						<code>
							//模型类$conection属性使用自定义连接
							<br/>
							protected $connection = 'MYDSN';
						</code>
					</p>
					<p>
						<code>
							//实例化模型时使用自定义连接
							<br/>
							$User = M('User','pre_','MYDSN'); 
						</code>
					</p>
				</example>
			</examples>
		</item>
		<item id="DB_NAME">
			<title>数据库名</title>
			<infomation>database名称</infomation>
		</item>
		<item id="DB_USER">
			<title>数据库用户名</title>
			<infomation>数据库用户名</infomation>
		</item>
		<item id="DB_PWD">
			<title>数据库密码</title>
			<infomation>数据库用户登录密码</infomation>
		</item>
		<item id="DB_PROT">
			<title>数据库端口</title>
			<infomation>默认值: 3306</infomation>
		</item>
		<item id="DB_CHARSET">
			<title>数据表字符集</title>
			<infomation>默认为：utf8</infomation>
		</item>
		<item id="DB_DEPLOY_TYPE">
			<title>数据库模式</title>
			<document>http://doc.thinkphp.cn/manual/distributed_database.html</document>
			<infomation>在主从模式下，数据库连接不能使用DSN方式</infomation>
			<examples>
				<example comment="DB_TYPE驱动配置">
					所有服务器都将使用统一的数据库驱动类型
				</example>
				<example comment="DB_HOST配置">
					所有服务器用逗号分隔开
					<br/>
					'DB_HOST'   => '192.168.0.1,192.168.0.2'
					<br/>
				</example>
				<example comment="DB_HOST特殊情况">
					如果使用同一服务器上的多个数据库，也必须写多次，例如
					'DB_HOST'   => '192.168.0.1,192.168.0.1'
					<br/>
				</example>
				<example comment="其他配置">
					<pre>其他配置根据情况按照DB_HOST的顺序进行对应配置:
'DB_USER'   => 'user1,user2',
'DB_PWD'    => 'pwd1,pwd2',
'DB_NAME'   => 'thinkphp',
//如果所有的都相同可以定义一个唯一值
'DB_PORT'   => '3306',
'DB_PREFIX' => 'think_',</pre>
				</example>
			</examples>
		</item>
		<item id="DB_RW_SEPARATE">
			<title>是否读写分离</title>
			<document>http://doc.thinkphp.cn/manual/distributed_database.html</document>
			<infomation>
				在读写分离的情况下，DB_HOST的第一个主机作为主服务器，负责写入数据，其余的都作为从服务器配置。
			</infomation>
			<examples>
				<example comment="注意">
					如果你用的是原生SQL：<br/>
					写操作必须用模型的execute方法，读操作必须用模型的query方法，否则会发生主从读写错乱的情况。
				</example>
			</examples>
		</item>
		<item id="DB_MASTER_NUM">
			<title>主服务器数量</title>
			<document>http://doc.thinkphp.cn/manual/distributed_database.html</document>
			<infomation>
				如果设置了读写分离和DB_MASTER_NUM参数，DB_HOST按顺序前面的几个配置都是主服务器配置信息，只负责写。后面的是从服务器，只负责读。
			</infomation>
		</item>
		<item id="DB_SLAVE_NO">
			<title>读服务器序号</title>
